import { Badge } from '../../../../components/ui/badge'
import { formatDate } from '../../lib/format'
import { PAYROLL_RUN_STATUS_META } from '../../lib/status-meta'
import type { PayrollRunDetail } from '../../types/payroll-types'

export function RunHeader({ run }: { run: PayrollRunDetail }) {
  const statusMeta = PAYROLL_RUN_STATUS_META[run.status]

  return (
    <div className="rounded-panel border border-line bg-surface p-5 shadow-panel">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-lg font-medium text-ink">{run.periodLabel}</h1>
            <Badge tone={statusMeta.tone}>{statusMeta.label}</Badge>
          </div>
          <p className="mt-0.5 text-sm text-muted">
            Pay period {formatDate(run.payPeriodStart)} – {formatDate(run.payPeriodEnd)} · Pay date{' '}
            {formatDate(run.payDate)}
          </p>
        </div>

        <div className="text-right text-xs text-muted">
          <p>{run.taxRuleSet.label}</p>
          <p>Payroll engine {run.payrollEngineVersion}</p>
        </div>
      </div>

      {run.status === 'failed' && run.failureReason ? (
        <p className="mt-4 rounded-lg border border-critical/30 bg-critical/5 px-3 py-2 text-xs text-critical">
          {run.failureReason}
        </p>
      ) : null}

      <div className="mt-4 flex flex-wrap gap-x-6 gap-y-1 text-xs text-muted">
        <span>
          Generated by {run.generatedBy} · {formatDate(run.generatedAt)}
        </span>
        {run.approvedBy && run.approvedAt ? (
          <span>
            Approved by {run.approvedBy} · {formatDate(run.approvedAt)}
          </span>
        ) : null}
      </div>
    </div>
  )
}
