import { Card, CardHeader } from '../../../../components/ui/card'
import { formatAmount } from '../../lib/format'
import { ComplianceWarningsList } from '../compliance-warnings-list'
import type { PayrollRunDetail } from '../../types/payroll-types'

export function SummaryTab({ run }: { run: PayrollRunDetail }) {
  const { summary } = run

  return (
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-3">
      <div className="space-y-5 lg:col-span-2">
        <Card>
          <CardHeader title="Compliance summary" description="What was calculated for this run" />
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
            <div>
              <p className="text-xs text-muted">Employees</p>
              <p className="mt-0.5 text-lg font-medium text-ink">{summary.employeeCount}</p>
            </div>
            <div>
              <p className="text-xs text-muted">Gross payroll</p>
              <p className="mt-0.5 text-lg font-medium text-ink">{formatAmount(summary.grossPay, summary.currency)}</p>
            </div>
            <div>
              <p className="text-xs text-muted">Employee deductions</p>
              <p className="mt-0.5 text-lg font-medium text-ink">
                {formatAmount(summary.totalEmployeeDeductions, summary.currency)}
              </p>
            </div>
            <div>
              <p className="text-xs text-muted">Employer contributions</p>
              <p className="mt-0.5 text-lg font-medium text-ink">
                {formatAmount(summary.totalEmployerContributions, summary.currency)}
              </p>
            </div>
            <div>
              <p className="text-xs text-muted">Net payroll</p>
              <p className="mt-0.5 text-lg font-medium text-ink">{formatAmount(summary.netPay, summary.currency)}</p>
            </div>
            <div>
              <p className="text-xs text-muted">Total employer cost</p>
              <p className="mt-0.5 text-lg font-medium text-ink">
                {formatAmount(summary.totalEmployerCost, summary.currency)}
              </p>
            </div>
          </div>
        </Card>

        <Card>
          <CardHeader title="Settings snapshot" description="Resolved settings captured when this run was generated" />
          <dl className="grid grid-cols-1 gap-x-6 gap-y-4 sm:grid-cols-2">
            <div>
              <dt className="text-xs text-muted">Tax rule set</dt>
              <dd className="mt-0.5 text-sm font-medium text-ink">{run.taxRuleSet.label}</dd>
            </div>
            <div>
              <dt className="text-xs text-muted">Tax rule version</dt>
              <dd className="mt-0.5 text-sm font-medium text-ink">{run.taxRuleSet.version}</dd>
            </div>
            <div>
              <dt className="text-xs text-muted">Payroll engine version</dt>
              <dd className="mt-0.5 text-sm font-medium text-ink">{run.payrollEngineVersion}</dd>
            </div>
            <div>
              <dt className="text-xs text-muted">Generated by</dt>
              <dd className="mt-0.5 text-sm font-medium text-ink">{run.generatedBy}</dd>
            </div>
          </dl>
          <p className="mt-4 text-xs text-muted">
            This snapshot is fixed to this run — later changes to payroll settings won't rewrite how {run.periodLabel} was
            calculated.
          </p>
        </Card>
      </div>

      <Card>
        <CardHeader title="Compliance warnings" />
        <ComplianceWarningsList warnings={run.complianceWarnings} />
      </Card>
    </div>
  )
}
