import {
  ArrowsClockwiseIcon,
  BellIcon,
  CalendarCheckIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CreditCardIcon,
  FolderIcon,
  GearIcon,
  HandCoinsIcon,
  MoneyIcon,
  ReceiptIcon,
  ShieldCheckIcon,
  SquaresFourIcon,
  UserCircleIcon,
  UsersIcon,
  WalletIcon,
  type Icon,
} from '@phosphor-icons/react'
import type { NavIconName } from './sidebar-nav-data'

export const NAV_ICONS: Record<NavIconName, Icon> = {
  dashboard: SquaresFourIcon,
  people: UsersIcon,
  payroll: MoneyIcon,
  spend: CreditCardIcon,
  compliance: ShieldCheckIcon,
  approvals: CheckCircleIcon,
  reports: ChartBarIcon,
  settings: GearIcon,
  profile: UserCircleIcon,
  leave: CalendarCheckIcon,
  payslips: ReceiptIcon,
  expenses: WalletIcon,
  reimbursements: ArrowsClockwiseIcon,
  salaryAdvance: HandCoinsIcon,
  documents: FolderIcon,
  notifications: BellIcon,
}
